name: Lint Dockerfile
on:
  push:
    branches:
      - master
      - docker-update
      - QA
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
